version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5051:5432'
    networks:
      - assembly-voting-network
    volumes:
      - postgresql:/var/docker/postgresql
    restart: unless-stopped

  assembly-voting:
    build:
      context: .
      dockerfile: Dockerfile
    image: assembly-voting:latest
    container_name: assembly-voting-service
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - assembly-voting-network

networks:
  assembly-voting-network:
volumes:
  postgresql: