version: '3.5'
volumes:
  postgresql:

services:
  postgres:
    image: postgres
    container_name: postgres_docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_assembly_voting
    ports:
      - '5051:5432'
    networks:
      - assembly-voting-network
    volumes:
      - postgresql:/var/docker/postgresql

  assembly-voting:
    build:
      context: .
      dockerfile: Dockerfile
    image: assembly-voting:latest
    container_name: assembly-voting-service
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - assembly-voting-network

networks:
  assembly-voting-network: